[Service]
ExecStartPre=/usr/sbin/ethtool -K ens18 tx off sg off tso off gso off gro off rx-gro-hw off
ExecStartPre=/usr/sbin/ethtool -K ens19 tx off sg off tso off gso off gro off rx-gro-hw off
ExecStart=
ExecStart=/usr/bin/suricata -D --af-packet -c /home/kbc/ips-security_capstone_projects/ips/suricata/suricata.yaml --pidfile /run/suricata.pid
ProtectHome=read-only
